---
# This playbook will install MariaDB and create db user and give permissions.

- name: Install MariaDB package
  apt:
    name:
    - mariadb-server
    state: latest

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/mysql/conf.d/custom.cnf
  notify:
  - restart mariadb

- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes

