---
- name: Install Apache
  apt:
    name:
    - apache2
    - libapache2-mod-php
    - libapache2-mod-geoip
    state: latest

- name: Copy apache main configuration file
  template: 
    src: httpd.conf 
    dest: /etc/apache2/apache2.conf
  notify: restart apache

- name: Copy apache configuration for wordpress
  template: 
    src: default.conf
    dest: /etc/apache2/sites-available/000-default.conf
  notify: restart apache

- name: Apache site configuration
  file:
    src: /etc/apache2/sites-available/000-default.conf 
    dest: /etc/apache2/sites-enabled/000-default.conf
    state: link
  notify: restart apache

- name: Alternative web folder (for bot attack)
  file:
    path: /var/www/html2
    state: directory
    mode: 0755

- name: Copy IP page index file
  template: src=index2.html dest=/var/www/html2/index.html

- name: "disable Apache module: MPM Event"
  apache2_module:
    state: absent
    name: mpm_event

- name: "enable Apache module: MPM Prefork"
  apache2_module:
    state: present
    name: mpm_prefork

- name: "enable Apache module: SSL"
  apache2_module:    
    state: present
    name: ssl

- name: "enable Apache modules: PHP7.4"
  apache2_module:
    state: present
    name: php7.4

- name: "enable Apache modules: Rewrite"
  apache2_module:
    state: present
    name: rewrite

- name: "enable Apache modules: HTTP/2"
  apache2_module:
    state: present
    name: http2


- name: http service state
  service: name={{ wp_apache }} state=started enabled=yes
